app/models/like.rb
app/models/match.rb
app/models/post.rb
app/models/request.rb
db/migrate/20240717111519_create_likes.rb
db/migrate/20240717111703_create_matches.rb
db/migrate/20240717111721_create_posts.rb
db/migrate/20240717111739_create_requests.rb
db/schema.rb
test/models/like_test.rb
test/models/match_test.rb
test/models/post_test.rb
test/models/request_test.rb

Added the requests, matches, likes and posts tables to the schema

added tables to the schema

---

db/migrate/20240717142315_add_details_to_likes.rb
db/migrate/20240717143028_add_details_to_posts.rb
db/migrate/20240717144924_add_details_to_matches.rb
db/migrate/20240717150300_add_details_to_requests.rb
db/schema.rb

Added multiple columns to all of the tables of the schema

Adding to tables

---

db/migrate/20240717152929_add_column_to_users.rb
db/schema.rb

added username and image_url to the users table

added username and image_url to the users table

---

app/models/like.rb
app/models/match.rb
app/models/post.rb
app/models/request.rb
app/models/user.rb
config/routes.rb

So the relationships between the user and requests, and also between user and matches is kind of tricky. I tried some stuff that I don't fully understand, but will get a TA's opinion on thursday.

set up relationships between models, could need some editing

---

app/models/like.rb
db/migrate/20240720112553_drop_likes.rb
db/schema.rb

dropped the likes table from the schema

---

app/controllers/users_controller.rb
app/views/users/show.html.erb
config/routes.rb

User show page that will be used as the profile page

added a user show page.

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb

Added username logic to the User table and then added that name to the navbar

added dynamic username to navbar

---

app/models/comment.rb
app/models/post.rb
db/migrate/20240722164742_create_comments.rb
db/migrate/20240722164839_add_details_to_comments.rb
db/schema.rb
test/models/comment_test.rb

Added the comments table. Also added the relationships to the model.

added the comments table to the schema

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Changed some styling inside header partial.

Updates to header

---

app/assets/stylesheets/application.scss

i just deleted some extra lines of code that was commented on the application.scss file

profile post page

---

app/controllers/application_controller.rb
app/policies/application_policy.rb
app/policies/post_policy.rb
test/policies/post_policy_test.rb

got rid of pundit

---

Gemfile.lock
app/assets/stylesheets/components/_button.scss
app/views/posts/index.html.erb
app/views/posts/show.html.erb

Amended CSS for like button
It is now an icon

working css for like button

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_comment.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/likes_controller.rb
app/controllers/matches_controller.rb
app/views/matches/index.html.erb
app/views/posts/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Created styling changes for the half way demo today. This is subject to change if anyone has any issues.

created styling changes

---

app/assets/stylesheets/pages/_index.scss
db/schema.rb

resized images

---

app/assets/stylesheets/application.scss
app/views/users/show.html.erb
db/schema.rb

Centred profile image on profile page

centred profile image

---

app/views/users/show.html.erb

Changed the logout link to make it a button

logout buttom

---

app/assets/stylesheets/pages/_profile.scss
app/views/users/show.html.erb

Removed user email from profile page

email removed

---

app/assets/stylesheets/components/_button.scss
app/views/posts/show.html.erb
app/views/users/show.html.erb

button formatting

---

app/assets/stylesheets/application.scss
db/schema.rb

updated the pics sizes

---

app/assets/stylesheets/components/_index.scss
app/views/matches/index.html.erb
db/seeds.rb

Adding some style in  the notifications page

styling the notification page

---

app/assets/stylesheets/components/_index.scss

I made sure the like button its in the same height as the rest of the buttons

align the like btn

---

app/assets/stylesheets/components/_index.scss
app/views/matches/index.html.erb

just added some initials as part of the avatar in the notification page

notification pages added initials

---

app/assets/stylesheets/components/_index.scss
app/controllers/matches_controller.rb
app/views/matches/index.html.erb
config/routes.rb

Added the cancel notification button, so now you can cancel any of the requests that you did, added some code in the routes.rb file and match.controller file . Also added some more divs so it looks a bit more like everything is in place and there is some space between them.

added the cancel notification button

---

app/assets/stylesheets/components/_index.scss

just aligned the buttons so all of them are in the same height

align buttons together

---

app/assets/stylesheets/components/_button.scss
app/views/posts/index.html.erb
db/schema.rb

Added a stroke to the like button

edited like button

---

app/assets/stylesheets/application.scss

just changed the posts border-size

changed the border size of the posts

---

app/assets/stylesheets/components/_navbar.scss

Added outline to notification icon

added outline

---

app/assets/stylesheets/components/_footer.scss

Changed background colour on bottom button

background

---

app/assets/stylesheets/application.scss

updated post

---

app/assets/stylesheets/components/_index.scss
app/views/matches/index.html.erb

added a background picture

---

app/assets/stylesheets/components/_index.scss

updated some stuff in the index page

updated some stuff

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_post_index.scss
app/views/matches/index.html.erb

updaing some extra stuff
